// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorReadingDataHub;

namespace SensorReadingDataHub.Migrations
{
    [DbContext(typeof(SensorReadingContext))]
    partial class SensorReadingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("SensorReadingDataHub.SensorReading", b =>
                {
                    b.Property<string>("DeviceSerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("COLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("DeviceSerialNumber", "Time");

                    b.ToTable("SensorReading");
                });
#pragma warning restore 612, 618
        }
    }
}
